version: '3'
services:
  eureka:
    ports:
    - "8761:8761"
    image: neerajjain/eureka
  queue:
    ports:
    - "61616:61616"
    - "8161:8161"
    image: rmohr/activemq
  mongo:
    ports:
    - "27017:27017"
    image: mongo
  simulator:
    volumes:
      - /tmp/position_tracker/not-started:/tmp/not-started
      - /tmp/position_tracker/started:/tmp/started
      - /tmp/position_tracker/finished:/tmp/finished
    ports:
    - "9090:9090"
    image: positionsimulator
  directions:
    ports:
    - "9080:9080"
    image: neerajjain/trip-directions
