FROM adoptopenjdk/openjdk11

MAINTAINER Neeraj Jain "https://hub.docker.com/u/neerajjain"

ADD positionsimulator-0.0.1-SNAPSHOT.jar positionsimulator.jar

CMD ["java", "-jar", "positionsimulator.jar"]
