global:
  slack_api_url: 'YOUR_SLACK_URL'
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 300m
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#kubernetes-alerts'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.message }}\n"
