apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 1
  template:  # Template for the POD
    metadata:
      labels:
        app: queue
    spec:
      containers:
        - name: queue
          image: rmohr/activemq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: position-simulator
spec:
  selector:
    matchLabels:
      app: position-simulator
  replicas: 1
  template:  # Template for the POD
    metadata:
      labels:
        app: position-simulator
    spec:
      containers:
        - name: position-simulator
          image: neerajjain/positionsimulator
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  template:  # Template for the POD
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracker
spec:
  selector:
    matchLabels:
      app: tracker
  replicas: 1
  template: # template for the POD
    metadata:
      labels:
        app: tracker
    spec:
      containers:
        - name: tracker
          image: neerajjain/vehicle-position-tracker
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: neerajjain/eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: neerajjain/position-tracker-api-gateway
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: neerajjain/position-tracker-webapp
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice

